# Generated by Django 6.0.1 on 2026-02-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('stellar_public_key', models.CharField(max_length=56, unique=True)),
                ('stellar_secret_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usdc', models.DecimalField(decimal_places=7, max_digits=12)),
                ('customer_phone', models.CharField(max_length=15)),
                ('memo', models.CharField(max_length=28)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.merchant')),
            ],
        ),
    ]
