# Generated by Django 6.0.1 on 2026-02-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_usdc',
            new_name='amount_xlm',
        ),
    ]
