# Generated by Django 6.0.1 on 2026-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_amount_usdc_transaction_amount_xlm'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=64),
        ),
    ]
