# Generated by Django 6.0.1 on 2026-02-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merchant_stellar_onchain_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=7, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=7, max_digits=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_usdc',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_wallet_public_key',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_xlm',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('app', 'App-based (Pooled Account)'), ('wallet', 'Self-custodied (Own Wallet)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('stellar_memo', models.CharField(blank=True, max_length=28, null=True, unique=True)),
                ('balance_usdc', models.DecimalField(decimal_places=7, default=0, max_digits=12)),
                ('stellar_public_key', models.CharField(blank=True, max_length=56, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_app',
            field=models.ForeignKey(blank=True, limit_choices_to={'customer_type': 'app'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_transactions', to='payments.customer'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usdc', models.DecimalField(decimal_places=7, max_digits=12)),
                ('payment_method', models.CharField(default='mobile_money', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'customer_type': 'app'}, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usdc', models.DecimalField(decimal_places=7, max_digits=12)),
                ('payout_method', models.CharField(default='mobile_money', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_approved', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'customer_type': 'app'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='payments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rebalance', 'Rebalancing'), ('reconciliation', 'Reconciliation'), ('deposit', 'Deposit Processed'), ('withdrawal', 'Withdrawal Processed'), ('alert', 'Alert Triggered'), ('manual_adjustment', 'Manual Adjustment')], max_length=20)),
                ('master_balance_before', models.DecimalField(decimal_places=7, max_digits=20)),
                ('master_balance_after', models.DecimalField(decimal_places=7, max_digits=20)),
                ('db_total_before', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('db_total_after', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_logs', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.deposit')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.withdrawal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_type', 'app'), ('phone_number__isnull', False)), models.Q(('customer_type', 'wallet'), ('stellar_public_key__isnull', False)), _connector='OR'), name='customer_type_field_consistency'),
        ),
    ]
