# Generated by Django 6.0.1 on 2026-02-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_dual_path_customer_treasury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_stellar', models.DecimalField(decimal_places=7, max_digits=16)),
                ('currency', models.CharField(choices=[('XLM', 'XLM'), ('USDC', 'USDC')], default='USDC', max_length=4)),
                ('payout_phone', models.CharField(blank=True, max_length=20)),
                ('payout_method', models.CharField(default='mobile_money', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_withdrawals_approved', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='payments.merchant')),
            ],
        ),
    ]
